Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataPribadiNetCoreMVC.Data;
using DataPribadiNetCoreMVC.Models;

namespace DataPribadiNetCoreMVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly DataPribadiDbContext _context;

        public EmployeesController(DataPribadiDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> IndexEmp()
        {
            var dataPribadiDbContext = _context.Employees.Include(e => e.DataDb).Include(e => e.JobTitle);
            return View(await dataPribadiDbContext.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> DetailsEmp(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.DataDb)
                .Include(e => e.JobTitle)
                .FirstOrDefaultAsync(m => m.EmpId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult CreateEmp()
        {
            ViewData["EmployeeName"] = new SelectList(_context.DataDbs, "Nik", "NamaLengkap");
            ViewData["JobTitles"] = new SelectList(_context.JobTitles, "Id", "JobTitle1");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEmp([Bind("EmpId,EmployeeName,JobTitles,Email,Phone,HiredDate,JobId,Country")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexEmp));
            }
            ViewData["EmployeeName"] = new SelectList(_context.DataDbs, "Nik", "NamaLengkap", employee.EmployeeName);
            ViewData["JobTitles"] = new SelectList(_context.JobTitles, "Id", "JobTitle1", employee.JobTitles);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> EditEmp(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["EmployeeName"] = new SelectList(_context.DataDbs, "Nik", "Nik", employee.EmployeeName);
            ViewData["JobTitles"] = new SelectList(_context.JobTitles, "Id", "JobTitle1", employee.JobTitles);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditEmp(string id, [Bind("EmpId,EmployeeName,JobTitles,Email,Phone,HiredDate,JobId,Country")] Employee employee)
        {
            if (id != employee.EmpId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmpId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(IndexEmp));
            }
            ViewData["EmployeeName"] = new SelectList(_context.DataDbs, "Nik", "Nik", employee.EmployeeName);
            ViewData["JobTitles"] = new SelectList(_context.JobTitles, "Id", "JobTitle1", employee.JobTitles);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> DeleteEmp(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.DataDb)
                .Include(e => e.JobTitle)
                .FirstOrDefaultAsync(m => m.EmpId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'DataPribadiDbContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexEmp));
        }

        private bool EmployeeExists(string id)
        {
          return (_context.Employees?.Any(e => e.EmpId == id)).GetValueOrDefault();
        }
    }
}

Controllers/TableViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace DataPribadiNetCoreMVC.Controllers
{
    public class TableViewController : Controller
    {
        public DataPribadiDbContext _context = new DataPribadiDbContext();

        public IActionResult IndexVM()
        {
            var country = _context.DataDbs.Include(d => d.Country);
            var data = country.ToList();
            var dept = _context.JobTitles.Include(d => d.Department);
            var jobtitle = dept.ToList();
            var tableVM = new tableVM
            {
                DataDbs= data,
                JobTitles= jobtitle
            };
            return View(tableVM);
        }
    }
}

Controllers/UnderController.cs
using Microsoft.AspNetCore.Mvc;

namespace DataPribadiNetCoreMVC.Controllers
{
    public class UnderController : Controller
    {
        public IActionResult UnderConstruction()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Project</title>
    <link rel="stylesheet" href="~/csl/jqueryui/themes/base/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/datatables/jquery.datatables.css" rel="stylesheet" />
    <link href="~/datatables/jquery.datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/csl/Custom.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-main border-bottom box-shadow mb-3">
            <div  class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Code</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown">Main Master Data</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="DataDBs" asp-action="Index">Candidate</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="IndexEmp">Employee</a>
                            </div>
                        </li>                        
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown">Additional Master Data</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="JobTitles" asp-action="IndexJB">Job Title</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Under" asp-action="UnderConstruction">Department</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Under" asp-action="UnderConstruction">Country</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="TableView" asp-action="IndexVM">All Table View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted">
        <div class="container">
            &copy; 2022 - Arief Ageng Susilo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/csl/jquery/jquery.js"></script>
    <script src="~/csl/jqueryui/jquery-ui.js"></script>
    <script src="~/csl/jquery-validate/jquery.validate.js"></script>
    <script src="~/csl/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/dateformat.js"></script>
    <script src="~/js/AutoHideAlert.js"></script>
    <script src="~/datatables/jquery.datatables.js"></script>
    <script src="~/datatables/jquery.datatables.min.js"></script>
    <script src="~/js/popper.js/umd/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>